import os

path = 'd:/AntiGravity_Projects/Personal/travel-quote-v2/src/app/builder/page.tsx'

with open(path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

def find_line(pattern):
    for i, line in enumerate(lines):
        if pattern in line:
            return i
    return -1

aside_start = find_line('<aside className="w-[480px]')

if aside_start == -1:
    print("Could not find aside start!")
    exit(1)

new_lines = lines[:aside_start]

# EXTREME SIMPLICITY REDO (No Boxes, Just Space)
extreme_redo = [
    '          <aside className="w-[480px] bg-white border-l border-[#e8eaed] flex flex-col shrink-0 sticky top-16 h-[calc(100vh-64px)] overflow-hidden shadow-2xl">\n',
    '            <div className="!px-20 !py-16 flex-1 overflow-y-auto space-y-16 custom-scrollbar">\n',
    '              \n',
    '              {/* Section 1: Package Selection (Simple & Flat) */}\n',
    '              <div className="space-y-8">\n',
    '                <div className="text-center">\n',
    '                   <p className="text-[10px] font-black uppercase tracking-[0.3em] text-text-tertiary">Select Proposed Package</p>\n',
    '                </div>\n',
    '                <div className="flex flex-col gap-4">\n',
    '                  {totals.packages.map((pkg, i) => {\n',
    '                    const pPreset = dbPackagePresets.find(p => p.title === pkg.name);\n',
    '                    const pkgId = pPreset?.id;\n',
    '                    const isSelected = selectedPackageId === pkgId;\n',
    '                    \n',
    '                    return (\n',
    '                      <div \n',
    '                        key={i} \n',
    '                        onClick={() => {\n',
    '                          setSelectedPackageName(pkg.name);\n',
    '                          setSelectedPackageId(pkgId || null);\n',
    '                        }}\n',
    '                        className={`w-full h-24 rounded-3xl border transition-all flex flex-col items-center justify-center gap-1 cursor-pointer ${\n',
    '                          isSelected \n',
    '                            ? "bg-[#1a2138] border-[#1a2138] text-white shadow-xl" \n',
    '                            : "bg-white border-gray-100 text-primary hover:border-primary/20 hover:shadow-sm"\n',
    '                        }`}\n',
    '                      >\n',
    '                        <span className={`text-[9px] font-black uppercase tracking-widest ${isSelected ? "text-white/40" : "text-text-tertiary"}`}>\n',
    '                          {pkg.name}\n',
    '                        </span>\n',
    '                        <div className="flex items-baseline gap-1.5">\n',
    '                          <span className={`text-sm font-bold ${isSelected ? "text-white/20" : "text-primary/10"}`}>₱</span>\n',
    '                          <span className="text-3xl font-black tracking-tighter italic leading-none">\n',
    '                            {pkg.total.toLocaleString()}\n',
    '                          </span>\n',
    '                        </div>\n',
    '                      </div>\n',
    '                    );\n',
    '                  })}\n',
    '                </div>\n',
    '              </div>\n',
    '\n',
    '              {/* Section 2: Adjustment List (Flat & Clean) */}\n',
    '              <div className="space-y-6">\n',
    '                <div className="flex justify-between items-center border-b border-gray-50 pb-4">\n',
    '                   <p className="text-[10px] font-black uppercase tracking-[0.3em] text-text-tertiary">Quote Adjustments</p>\n',
    '                   <button \n',
    '                     onClick={() => setIsAdjustOpen(!isAdjustOpen)}\n',
    '                     className={`h-7 w-7 flex items-center justify-center rounded-full transition-all ${isAdjustOpen ? "bg-primary text-white" : "text-primary bg-gray-50 hover:bg-gray-100"}`}\n',
    '                   >\n',
    '                     {isAdjustOpen ? <X size={12} /> : <Plus size={12} />}\n',
    '                   </button>\n',
    '                </div>\n',
    '\n',
    '                {isAdjustOpen && (\n',
    '                  <div className="p-6 bg-gray-50/50 rounded-2xl space-y-3 animate-in fade-in slide-in-from-top-2">\n',
    '                    <input \n',
    '                      type="text" \n',
    '                      placeholder="Fee Label" \n',
    '                      className="w-full bg-white border border-gray-100 rounded-xl px-4 py-2.5 text-xs font-bold outline-none ring-primary/20 focus:ring-1"\n',
    '                      value={newFeeName}\n',
    '                      onChange={(e) => setNewFeeName(e.target.value)}\n',
    '                    />\n',
    '                    <div className="flex gap-2">\n',
    '                      <input \n',
    '                        type="number" \n',
    '                        placeholder="Amount" \n',
    '                        className="flex-1 bg-white border border-gray-100 rounded-xl px-4 py-2.5 text-xs font-bold outline-none ring-primary/20 focus:ring-1"\n',
    '                        value={newFeeAmount}\n',
    '                        onChange={(e) => setNewFeeAmount(e.target.value)}\n',
    '                      />\n',
    '                      <button \n',
    '                        onClick={handleAddCustomExtraFee}\n',
    '                        className="px-5 py-2.5 bg-primary text-white rounded-xl text-[10px] font-black uppercase tracking-widest"\n',
    '                      >\n',
    '                        Add\n',
    '                      </button>\n',
    '                    </div>\n',
    '                  </div>\n',
    '                )}\n',
    '\n',
    '                <div className="divide-y divide-gray-50">\n',
    '                  {extraFees.map((fee) => (\n',
    '                    <div key={fee.id} className="flex justify-between items-center py-4 text-xs group">\n',
    '                      <span className="text-text-tertiary font-black uppercase tracking-widest text-[8px] italic">{fee.name}</span>\n',
    '                      <div className="flex items-center gap-4">\n',
    '                        <span className="font-black text-primary italic text-sm">₱ {fee.amount.toLocaleString()}</span>\n',
    '                        <button onClick={() => setExtraFees(extraFees.filter(f => f.id !== fee.id))} className="text-gray-200 hover:text-rose-500 opacity-0 group-hover:opacity-100 transition-all"><Trash2 size={12} /></button>\n',
    '                      </div>\n',
    '                    </div>\n',
    '                  ))}\n',
    '\n',
    '                  <div className="flex justify-between items-center py-6">\n',
    '                    <div className="flex items-center gap-2">\n',
    '                       <CreditCard size={12} className="text-emerald-500 opacity-40" />\n',
    '                       <span className="font-black text-[9px] uppercase tracking-widest text-text-tertiary">Discount Applied</span>\n',
    '                    </div>\n',
    '                    <div className="flex items-center gap-1 font-black italic text-emerald-600">\n',
    '                      <span className="text-[10px]">- ₱</span>\n',
    '                      <input \n',
    '                        type="number" \n',
    '                        className="w-20 text-right bg-transparent border-none focus:ring-0 p-0 text-sm font-black italic tracking-tighter" \n',
    '                        placeholder="0" \n',
    '                        value={discount || ""} \n',
    '                        onChange={(e) => setDiscount(parseFloat(e.target.value) || 0)} \n',
    '                      />\n',
    '                    </div>\n',
    '                  </div>\n',
    '                </div>\n',
    '              </div>\n',
    '\n',
    '              {/* Section 3: Final Balance (Massive Centered Text) */}\n',
    '              <div className="flex flex-col items-center space-y-6 pt-4">\n',
    '                 <div className="w-full space-y-3 pb-8 border-b border-gray-50">\n',
    '                    <div className="flex justify-between text-[9px] font-black uppercase tracking-widest text-text-tertiary/60">\n',
    '                      <span>Base Package</span>\n',
    '                      <span>₱ {totals.selectedPkgPrice.toLocaleString()}</span>\n',
    '                    </div>\n',
    '                    <div className="flex justify-between text-[9px] font-black uppercase tracking-widest text-text-tertiary/60">\n',
    '                      <span>Adjustments</span>\n',
    '                      <span>₱ {totals.totalExtraFees.toLocaleString()}</span>\n',
    '                    </div>\n',
    '                    <div className="flex justify-between text-[9px] font-black uppercase tracking-widest text-emerald-600">\n',
    '                      <span>Discount</span>\n',
    '                      <span>- ₱ {discount.toLocaleString()}</span>\n',
    '                    </div>\n',
    '                 </div>\n',
    '                 \n',
    '                 <div className="flex flex-col items-center gap-3">\n',
    '                    <span className="text-[11px] font-black uppercase tracking-[0.4em] text-text-tertiary/30">Final Balance</span>\n',
    '                    <div className="flex items-baseline gap-2">\n',
    '                      <span className="text-base font-black text-primary/10 italic">₱</span>\n',
    '                      <span className="text-6xl font-black italic tracking-tighter text-primary">{totals.grandTotal.toLocaleString()}</span>\n',
    '                    </div>\n',
    '                 </div>\n',
    '              </div>\n',
    '\n',
    '              {/* Section 4: Operational Context */}\n',
    '              <div className="space-y-6 pb-12">\n',
    '                 <div className="text-center">\n',
    '                    <p className="text-[10px] font-black uppercase tracking-[0.3em] text-text-tertiary">Operational Context</p>\n',
    '                 </div>\n',
    '                 <textarea \n',
    '                    className="w-full min-h-[160px] p-8 bg-gray-50/50 border-transparent rounded-[32px] text-xs font-bold leading-relaxed resize-none focus:bg-white focus:border-gray-100 transition-all outline-none text-text-secondary placeholder:text-text-tertiary/20 shadow-inner" \n',
    '                    placeholder="Add operational details..."\n',
    '                    value={quote.notes}\n',
    '                    onChange={(e) => setQuote({...quote, notes: e.target.value})}\n',
    '                 />\n',
    '              </div>\n',
    '            </div>\n',
    '\n',
    '            {/* Sticky Action Footer */}\n',
    '            <div className="px-12 py-8 border-t border-[#f0f2f5] bg-white flex items-center gap-3">\n',
    '               {initialQuotationText && (\n',
    '                 <button \n',
    '                   onClick={() => {\n',
    '                     setPreviewText(initialQuotationText);\n',
    '                     setIsPreviewOpen(true);\n',
    '                   }}\n',
    '                   className="h-12 px-5 bg-[#f8f9fb] border border-[#e8eaed] text-text-tertiary rounded-2xl font-black text-[9px] tracking-[0.1em] uppercase hover:bg-[#f0f2f5] hover:text-primary transition-all flex items-center justify-center gap-2 shrink-0"\n',
    '                 >\n',
    '                   <Copy size={14} className="opacity-40" /> View Copy\n',
    '                 </button>\n',
    '               )}\n',
    '               <button \n',
    '                 onClick={handleFinish}\n',
    '                 disabled={isSaving || !quoteId || quote.items.length === 0}\n',
    '                 className="flex-1 h-12 bg-primary text-white rounded-2xl font-black text-[10px] tracking-[0.2em] uppercase shadow-lg shadow-primary/10 hover:opacity-95 active:scale-[0.98] transition-all flex items-center justify-center gap-3 group disabled:opacity-30 disabled:grayscale disabled:cursor-not-allowed"\n',
    '               >\n',
    '                 {initialQuotationText ? "Re-issue Quote" : "Generate Quote"} \n',
    '                 <ArrowRight size={18} className="group-hover:translate-x-1 transition-transform" />\n',
    '               </button>\n',
    '            </div>\n',
    '          </aside>\n',
    '        </div>\n',
    '      </div>\n',
    '\n',
    '      {isPreviewOpen && (\n',
    '        <QuotationPreviewModal \n',
    '          text={previewText} \n',
    '          setText={setPreviewText} \n',
    '          onClose={() => setIsPreviewOpen(false)}\n',
    '          onSave={finalizeSave}\n',
    '          onConfirm={handleConfirmQuote}\n',
    '          onCancel={handleCancelQuote}\n',
    '          isSaving={isSaving}\n',
    '        />\n',
    '      )}\n',
    '    </div>\n',
    '  );\n',
    '}\n',
    '\n',
    'function QuotationPreviewModal({ text, setText, onClose, onSave, onConfirm, onCancel, isSaving }: any) {\n',
    '  const handleCopy = () => {\n',
    '    navigator.clipboard.writeText(text);\n',
    '    alert("Quotation copied to clipboard!");\n',
    '  };\n',
    '\n',
    '  const handlePrint = () => {\n',
    '    window.print();\n',
    '  };\n',
    '\n',
    '  return (\n',
    '    <div className="fixed inset-0 z-[100] flex items-center justify-center p-6 bg-black/60 backdrop-blur-md">\n',
    '      <motion.div \n',
    '        initial={{ opacity: 0, scale: 0.9, y: 20 }}\n',
    '        animate={{ opacity: 1, scale: 1, y: 0 }}\n',
    '        className="bg-white rounded-[40px] w-full max-w-xl shadow-2xl flex flex-col max-h-[80vh] overflow-hidden border border-white/20 relative"\n',
    '      >\n',
    '        <div className="px-10 py-6 border-b border-[#f0f2f5] bg-white text-center relative">\n',
    '          <h3 className="text-lg font-black text-primary tracking-tight leading-none">Quotation Preview</h3>\n',
    '          <p className="text-[8px] text-text-tertiary font-bold uppercase tracking-widest mt-1.5">Final Review & Edit</p>\n',
    '          <button onClick={onClose} className="absolute top-4 right-4 p-2 hover:bg-[#f0f2f5] rounded-full transition-colors active:scale-90 text-text-tertiary">\n',
    '            <X size={16} />\n',
    '          </button>\n',
    '        </div>\n',
    '\n',
    '        <div className="flex-1 overflow-y-auto !px-12 !py-8 bg-white custom-scrollbar">\n',
    '          <div className="relative group">\n',
    '            <div className="absolute -top-4 right-0 text-[7px] uppercase font-black tracking-widest text-primary/10 group-hover:text-primary/40 transition-colors italic">Editable Zone</div>\n',
    '            <textarea \n',
    '              className="w-full bg-transparent border-none focus:ring-0 p-0 text-[13px] leading-[1.6] text-text-secondary outline-none resize-none overflow-hidden font-medium" \n',
    '              value={text}\n',
    '              onChange={(e) => setText(e.target.value)}\n',
    '              rows={1}\n',
    '              onInput={(e: any) => {\n',
    '                e.target.style.height = "auto";\n',
    '                e.target.style.height = e.target.scrollHeight + "px";\n',
    '              }}\n',
    '              ref={(el) => {\n',
    '                if (el) {\n',
    '                  el.style.height = "auto";\n',
    '                  el.style.height = el.scrollHeight + "px";\n',
    '                }\n',
    '              }}\n',
    '            />\n',
    '          </div>\n',
    '        </div>\n',
    '\n',
    '        <div className="px-10 py-8 bg-white border-t border-[#f0f2f5] flex items-center justify-center gap-2 print:hidden shrink-0">\n',
    '           <button \n',
    '             onClick={handleCopy}\n',
    '             className="!h-9 !px-4 bg-[#6366f1]/10 text-[#6366f1] rounded-xl font-bold text-[9px] uppercase tracking-widest hover:bg-[#6366f1] hover:text-white transition-all flex items-center justify-center gap-2"\n',
    '           >\n',
    '             <Copy size={12} /> Copy\n',
    '           </button>\n',
    '\n',
    '           <button \n',
    '             onClick={handlePrint}\n',
    '             className="!h-9 !px-4 bg-[#1e293b]/10 text-[#1e293b] rounded-xl font-bold text-[9px] uppercase tracking-widest hover:bg-[#1e293b] hover:text-white transition-all flex items-center justify-center gap-2"\n',
    '           >\n',
    '             <Printer size={12} /> Print\n',
    '           </button>\n',
    '\n',
    '           <div className="w-px h-5 bg-[#e8eaed] mx-1" />\n',
    '\n',
    '           <button \n',
    '             onClick={() => onSave()}\n',
    '             disabled={isSaving}\n',
    '             className="!h-9 !px-6 bg-[#1a2138] text-white rounded-xl font-black text-[9px] tracking-[0.1em] uppercase hover:opacity-90 active:scale-[0.98] transition-all flex items-center justify-center gap-2 shadow-lg shadow-primary/10"\n',
    '           >\n',
    '             <Save size={14} /> {isSaving ? "Finishing..." : "Save and Close"}\n',
    '           </button>\n',
    '        </div>\n',
    '      </motion.div>\n',
    '    </div>\n',
    '  );\n',
    '}\n'
]

new_lines = new_lines + extreme_redo

with open(path, 'w', encoding='utf-8') as f:
    f.writelines(new_lines)

print("Extreme Simplicity Restoration applied successfully!")
